In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# Import datasets, classifiers and performance metrics
from sklearn import datasets,svm,tree, metrics
import sklearn

In [2]:
## The digits datas
fashion_train = pd.read_csv('fashion-mnist_train.csv')
fashion_test = pd.read_csv('fashion-mnist_test.csv')
print(fashion_train.columns)
trainX = np.array(fashion_train)[:,1:]
testX = np.array(fashion_test)[:,1:]
trainY = np.array(fashion_train)[:,0]
testY = np.array(fashion_test)[:,0]
print(trainX.shape)
print(trainY.shape)

Index(['label', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=785)
(60000, 784)
(60000,)


In [3]:
classifier = tree.DecisionTreeClassifier()
#classifier = sklearn.linear_model.Perceptron()
classifier.fit(trainX, trainY)

DecisionTreeClassifier()

In [4]:
predictedY = classifier.predict(testX)

In [5]:
print('Accuracy:', metrics.accuracy_score(predictedY, testY))
print('Precision:',metrics.precision_score(predictedY, testY, average=None))
print('Recall:',metrics.recall_score(predictedY, testY,average=None))
print('Confusion Matrix:',metrics.confusion_matrix(predictedY, testY))

Accuracy: 0.7995
Precision: [0.738 0.962 0.684 0.827 0.693 0.877 0.554 0.865 0.899 0.896]
Recall: [0.72423945 0.94965449 0.7037037  0.8253493  0.67808219 0.90226337
 0.55511022 0.85728444 0.91734694 0.88450148]
Confusion Matrix: [[738   4  24  43  11   2 170   0  26   1]
 [  7 962   4  25   4   1  10   0   0   0]
 [ 20   4 684  13 140   0  97   0  14   0]
 [ 42  19  15 827  50   1  40   0   6   2]
 [  9   4 142  49 693   0 109   1  14   1]
 [  2   1   3   1   1 877   1  55   9  22]
 [167   3 118  37  96   1 554   0  20   2]
 [  1   0   0   0   0  62   0 865   9  72]
 [ 14   3   9   5   4  21  19   2 899   4]
 [  0   0   1   0   1  35   0  77   3 896]]


In [ ]:
classifier2 = svm.SVC(gamma=0.001)
classifier2.fit(trainX, trainY)
predictedY = classifier2.predict(testX)

In [ ]:
print('Accuracy:', metrics.accuracy_score(predictedY, testY))
print('Precision:',metrics.precision_score(predictedY, testY, average=None))
print('Recall:',metrics.recall_score(predictedY, testY,average=None))
print('Confusion Matrix:',metrics.confusion_matrix(predictedY, testY))

In [ ]:
classifier3 = sklearn.linear_model.SGDClassifier()
classifier3.fit(trainX, trainY)
predictedY = classifier3.predict(testX)

In [ ]:
print('Accuracy:', metrics.accuracy_score(predictedY, testY))
print('Precision:',metrics.precision_score(predictedY, testY, average=None))
print('Recall:',metrics.recall_score(predictedY, testY,average=None))
print('Confusion Matrix:',metrics.confusion_matrix(predictedY, testY))